In [1]:
#Importare TensorFlow

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.19.0


In [4]:
#Creare Tensor con tf.constant

In [5]:
scalare = tf.constant(2)
scalare

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
scalare.ndim

0

In [7]:
vettore = tf.constant([10, 10])
vettore

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vettore.ndim

1

In [9]:
matrice = tf.constant([[10, 7],
                      [10, 7]])
matrice

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [10]:
matrice.ndim

2

In [11]:
# Creare un'altra matrice
matrice2 = tf.constant([[10., 7.], [3., 2.], [5., 6.]], dtype=tf.float16) #specifichiamo il dtypem perché in automatico prende l'integer.
# Più è alto il numero, più è alta la precisione ma anche lo spazio richiesto in memoria.
# Forzare la matrice mi permette di risolvere un errore Dtype
matrice2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  6.]], dtype=float16)>

In [13]:
matrice2.ndim

2

In [18]:
# Creiamo un Tensor in modo da avere 3 dimensioni!
tensore = tf.constant([[[1, 2, 3],
 [4, 5, 6]],
  [[7, 8, 9],
   [10, 11, 12]],
    [[13, 14, 15],
     [16, 17, 18]]])
tensore

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [22]:
tensore.ndim

3

In [23]:
#Definizioni:
# Scalare = singolo numero (NO dimensioni)
# Vettore = numero con direzione (dal concetto di fisica del vettore)
# Matrice: un Array 2D di numeri
# Tensor: un Array nD di numeri (quindi anche uno scalare, se ha 0 dimensioni!)

In [34]:
# Usiamo la forma Variable
tensor_variable = tf.Variable([10, 7])
tensor_costante = tf.constant([10, 7])
tensor_variable, tensor_costante

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [36]:
# Non possiamo semplicemente assegnare al tensor con indice [n] un nuovo valore.
# Proviamo con .assign()
tensor_variable[0].assign(7)
tensor_variable
# NB. Con un tensor costante NON posso modificarlo! Nè con assign, nè facendo index[n] = NuovoValore
# I Tensor costanti non possono essere modificati e quindi hanno un uso diverso - di solito TensorFlow sceglie direttamente lui. Se dobbiamo scegliere e siamo in dubbio, meglio un Tensor variable.

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [38]:
# Random Tensor: Tensor di dimensione arbitraria e con numeri random
# Facciamo due Tensor random (ma uguali)
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [41]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [43]:
random_1, random_2, random_1 == random_2 # In questo modo confrontiamo i Tensor e tutti i valori corrispondenti tra loro!

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [49]:
random_3 = tf.random.Generator.from_seed(7)
random_3 = random_3.normal(shape=(3, 2))
random_3, random_3 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [51]:
# Come cambiare ordine di un tensor random (es. se ho tutti dati ordinati e la rete neurale potrebbe iniziare ad imparare con un bias). Serve per disordinare i dati
not_shuffle = tf.constant([[10, 7],
 [3, 5],
  [2, 1]])
not_shuffle


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  1]], dtype=int32)>

In [53]:
shuffle_tensor = tf.random.shuffle(not_shuffle)
shuffle_tensor
# Mescola ma solo nella prima dimensione! Quindi in questo caso mescola le coppie, ma non i numeri dentro le coppie (che sarebbero la seconda dimensione)
# Ogni volta che ricarico, ho un ordine diverso

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 2,  1],
       [10,  7]], dtype=int32)>

In [61]:
# Se uso il set_seed invece, rimane lo stesso ordine!
shuffle_tensor = tf.random.shuffle(not_shuffle, seed=42)
shuffle_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  1],
       [ 3,  5]], dtype=int32)>

In [63]:
rand_tensor_1 = tf.random.Generator.from_seed(42)
rand_tensor_1 = rand_tensor_1.normal(shape=(2, 5))
rand_tensor_1

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284]],
      dtype=float32)>

In [65]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (4,2))
random_2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [68]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3,3))
random_3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [73]:
random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.normal(shape = (8, 2))
random_4

<tf.Tensor: shape=(8, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993],
       [-0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ]], dtype=float32)>

In [75]:
random_5 = tf.random.Generator.from_seed(42)
random_5 = random_5.normal(shape=(2, 6))
random_5

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 , -0.57166284,  0.1480774 ,
        -0.23362993]], dtype=float32)>

In [77]:
random_6 = tf.random.Generator.from_seed(42)
random_6 = random_6.normal(shape= (3, 2, 4))
random_6

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
      dtype=float32)>